<!--<div>-->
<!--    <div>-->
<!--        <h4>Custom Tab</h4>-->
<!--    </div>-->
<!--    <div id="group_fields4">-->
<!--        <label for="custom_field">Custom Field</label>-->
<!--        <input type="text" class="input-text" name="custom_field" id="custom_field" />-->
<!--    </div>-->
<!--</div>-->
<div>
    <div>
        <h4>Custom Tab</h4>
    </div>
    <div id="group_fields4">
    </div>
</div>